// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCA4z5Gv-BlB9sTMRDbISJ0lKfOeQk1zW0',
    appId: '1:34992871610:web:5378cc9b65a1134f478a83',
    messagingSenderId: '34992871610',
    projectId: 'bitirme-33025',
    authDomain: 'bitirme-33025.firebaseapp.com',
    storageBucket: 'bitirme-33025.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBzrKzByGr6xx2PpdqJaSf2yj0HOuGGE-8',
    appId: '1:34992871610:android:426dca1f901e53a8478a83',
    messagingSenderId: '34992871610',
    projectId: 'bitirme-33025',
    storageBucket: 'bitirme-33025.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyANG1sMhm5ZXg4a_-y4tkGS4mKvCiWahfs',
    appId: '1:34992871610:ios:2233b6d2f9fef08d478a83',
    messagingSenderId: '34992871610',
    projectId: 'bitirme-33025',
    storageBucket: 'bitirme-33025.appspot.com',
    iosBundleId: 'com.example.sorucevap',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyANG1sMhm5ZXg4a_-y4tkGS4mKvCiWahfs',
    appId: '1:34992871610:ios:2233b6d2f9fef08d478a83',
    messagingSenderId: '34992871610',
    projectId: 'bitirme-33025',
    storageBucket: 'bitirme-33025.appspot.com',
    iosBundleId: 'com.example.sorucevap',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCA4z5Gv-BlB9sTMRDbISJ0lKfOeQk1zW0',
    appId: '1:34992871610:web:319da3f79993ebb6478a83',
    messagingSenderId: '34992871610',
    projectId: 'bitirme-33025',
    authDomain: 'bitirme-33025.firebaseapp.com',
    storageBucket: 'bitirme-33025.appspot.com',
  );
}
